spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update

  #disable liquibase at start-up
  liquibase:
    enabled: false

# Modify the port befor 8999 and then connect to 8081 because the 8080 the port is used for other applications and we wave must conflict.
server:
  port: 8081